### ISSUE TITLE
Support for ActiveRecord enum 

### ISSUE THREAD

**Issue by grzesiek** [justinfrench/formtastic#1059]
Hi !

I would be nice to use formtastic with enum fields introduced in Rails 4.1:
http://api.rubyonrails.org/v4.1.0/classes/ActiveRecord/Enum.html

Grzegorz

**Comment by dallas** [comment]
There’s also the case of custom defined enum values, as in:

```ruby
class SomeModel < ActiveRecord::Base
  enum status: {
    brand_new: "Brand New",
    less_new: "Less New",
    old: "Not So New"
  }
end
```

We’ve found that in this case we have to do this in `ActiveAdmin` (which uses Formtastic under the hood):

```ruby
form do |f|
  f.inputs do
    input :status, as: :select, collection: SomeModel.statuses.map(&:reverse)
  end
end
```

Which works just fine, but maybe that should be the default for such an enum input if Formtastic decides to support it?

**Comment by dallas** [comment]
I see that Formtastic does support enums now (as `collection_from_enum`) but it assumes the array-style syntax which also assumes integer values. Even the Rails enum docs only gives an example of using custom integer values in the hash-style syntax, but we had string columns already with values and we were delighted to discover that if you supply custom string values to your enum keys, it’ll just properly store those in the database and do all of its other fanciness (scopes, instance methods, etc.) as expected as well. For some reason, using just the `as: :select` option and letting it default to the `collection_from_enum` collection doesn’t work in our app. We don’t need the right-side values to be the labels, necessarily, but we do apparently need the left-side values to be the actual values of the options. Any chance you’ll think about supporting this somewhat hackish approach to enums? I’ll happily open a new issue if so 😄

**Comment by justinfrench** [comment]
Hi @dallas, feel free to create an issue, but the reality is I probably won't be motivated to implement any time soon since there seems to be a work-around. A well-defined issue with examples would make it more likely,. but really, a pull-request is the way to give it the best chance ;)
