### ISSUE TITLE
Remove support for deprecated 3.0 custom class methods

### ISSUE THREAD

**Issue by justinfrench** [justinfrench/formtastic#1104]
3.1.0 added new configurations for custom class finders with namespacing, and deprecated the old methods that some other libraries were subclassing (`input_class`, `custom_input_class_name`, `standard_input_class_name`, `action_class`, `custom_action_class_name`, `standard_action_class_name`, `input_class_by_trying`, etc). Pretty much anything with the `@deprecated` tag right now.

Any chance you're keen on this @mikz? It's probably about time I add you as a collaborator if you're keen?

**Comment by mikz** [comment]
Closed by #1139
