### ISSUE TITLE
Unable to find input class InetInput

### ISSUE THREAD

**Issue by rodrigopinto** [justinfrench/formtastic#1115]
Hi guys. I am using activeadmin on my models and I came across with a error caused by formtastic that is used behind activeadmin.

```
Formtastic::UnknownInputError at /admin/users/1/edit
Unable to find input class InetInput
```

When using a devise model, desive adds two columns as `inet`([network address type](http://www.postgresql.org/docs/9.1/static/datatype-net-types.html)), but there isn't a InetInput class declared on formtastic, so [input_helper.rb](https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/helpers/input_helper.rb#L330) can not resolve the lookup for the correct class to instantiate.

**Comment by mitio** [comment]
I think that the inet fields should be treated as string by default. They're used by default for trackable Devise models on PostgreSQL and it's a bit annoying to have to redefine the whole form for the resource because of these inet fields. If the form is not redefined, an exception will be raised.

**Comment by timoschilling** [comment]
@justinfrench what do you thing about a `DefaultInput` or `FallbackInput`, which is used for all unknown inputs?

**Comment by justinfrench** [comment]
@timoschilling @mitio We already fallback to `StringInput` in many cases. I think the problem here is that we don't have a fallback to `StringInput` when we're mapping database column types to inputs. I've created a new issue #1146 for this, would love help patching :)
