### ISSUE TITLE
Rails 4.2 deprecation on column_for

### ISSUE THREAD

**Issue by cpence** [justinfrench/formtastic#1117]
Similar to #1080, but I was advised to open a new issue. I'm using:

- Rails 4.2.0.rc3
- Formtastic 3.1.2

Formtastic is not explicitly configured, but is only used by ActiveAdmin (git HEAD, the beta of 1.0; revision f51d96dddb).

When I run my RSpec suite, I see the following deprecation warning (five or six times):

> DEPRECATION WARNING: `#column_for_attribute` will return a null object for non-existent columns in Rails 5. Use `#has_attribute?` if you need to check for an attribute's existence. (called from maxlength at /usr/local/Cellar/rbenv/0.4.0/versions/2.1.5/lib/ruby/gems/2.1.0/gems/formtastic-3.1.2/lib/formtastic/inputs/base/stringish.rb:27)

It looks to me like the trouble is at lib/formtastic/inputs/base/database.rb, line 7, where there's a call to the `column_for_attribute` method that's not wrapped in `ActiveSupport::Deprecation.silence`.

**Comment by justinfrench** [comment]
Just pushed new gem 3.1.3 with this patch in it FYI

**Comment by cpence** [comment]
Great, thanks so much!
