### ISSUE TITLE
`as: :datetime_picker` does not work in Safari and Firefox

### ISSUE THREAD

**Issue by cohart** [justinfrench/formtastic#1121]
I found several references to this issue but they were all in relation to Rails 3/2. I'm running Rails 4.1 and am using Formtastic in conjunction with ActiveAdmin. 

Simply speaking I have a form in a controller that uses the `as: :datetime_picker` selector. The calendar drop down works fine in Chrome but doesn't work in Safari and Firefox.

Is this a known issue or am I just missing some step?
```
 form :html => { multipart: true } do |f|
    f.inputs :new_topic do
      f.input :title
      f.input :slug
      f.input :release_date, label: "Release Topic At", as: :datetime_picker
      f.input :cover_photo, as: :file, label: "Cover Photo"
      f.input :category, as: :select,
        collection: ['...', '...', '...', '...', '...']
    end
    f.actions
  end
```

Works fine in chrome, but looks like this in Safari and FireFox, there are no console errors and the html generated is the same across the three browers.
![screen shot 2015-01-07 at 12 47 50 pm](https://cloud.githubusercontent.com/assets/5641925/5650380/e32380fe-966b-11e4-843c-6edf0ef341c1.png)

**Comment by justinfrench** [comment]
That's how Safari renders or implements a HTML date input (`<input type="date">`), sorry. Nothing Formtastic can do about that. We also provide `:as => :datetime_select` which is more like what Rails does. Another option is a polyfill. Check out the information and suggestions on http://html5please.com under `<input type="date">`:

> There are many date inputs: datetime-local, date, time, month, week that should provide a datepicker to the user. For a long time, WebKit offered a spinner UI on these inputs, but this was an incomplete implementation (and has since been removed). A few polyfills offer a proper datepicker UI, if the feature is not offered natively. We suggest you use Modernizr to detect this feature, as it has correctly detected these features, regardless of WebKit's partial implementation or other browser bugs. Recommended polyfills: webshims, html5widgets.

Closing this.

**Comment by cohart** [comment]
Word word. Thanks much!
