### ISSUE TITLE
Allow has_many :allow_destroy to accept string for label

### ISSUE THREAD

**Issue by lordjavac** [justinfrench/formtastic#1129]
Currently the :allow_destroy parameter for has_many in a form accepts a boolean to indicate whether it should be present or not. It would be nice to pass a string to be able to change the label on the generated checkbox.

I think this would help the readability of the destroy action when used on a join model.

What I'd like would look something like:

```ruby
semantic_form_for @category do |f|
  ...
  f.has_many :things, allow_destroy: 'Remove from this category' do |thing|
    ...
  end
end
```

Which would use the given string for the destroy label instead of the default "Destroy" that is currently in place.

**Comment by justinfrench** [comment]
Hello, I think `f.has_many` is provided by active admin, not Formtastic. Closing.
