### ISSUE TITLE
Default classes for input, wrapper and label in initializer

### ISSUE THREAD

**Issue by Tab10id** [justinfrench/formtastic#1131]
For unification form styles in application

**Comment by justinfrench** [comment]
Formtastic was designed long before CSS frameworks like Bootstrap or before there were any solid opinions on how forms should be marked-up. I'm not saying we'll _never_ implement these features, but other libraries like Simple Form already do a much better job and were designed with this in mind.

If someone worked up a patch I would strongly consider adding it, but I'm not motivated to work on such a feature or have this issue hanging around for months or years, so I'm closing this for now.
