### ISSUE TITLE
Custom inputs from app/inputs aren't loaded (?)

### ISSUE THREAD

**Issue by ezuk** [justinfrench/formtastic#1140]
Hello,

Using formtastic formtastic 3.1.3 and Rails 4.2.0, I created a file `app/inputs/card_back_input.rb` which says:

```
class CardBackInput < FormTastic::Inputs::StringInput

  def to_html
    super.merge(class: "flexible-text-area")
  end

  end
```

I try to use it in my form (using the Slim templating language) like so:

`f.input :back_content,  as: :card_back`

To which I get back: `Unable to find input class for card_back`.

Digging through the stack, I eventually get to `Formtastic::FormBuilder#input_class_by_trying` that yields `NameError: uninitialized constant FormTastic`.

To me, it looks like the card_back_input file I created simply doesn't get loaded, but I'm not sure if that's really the case or if there's another issue here. I followed the docs as closely as I could, not sure what I missed. Any help would be most appreciated.

**Comment by justinfrench** [comment]
Change `FormTastic` to `Formtastic` to fix this error at least: `NameError: uninitialized constant FormTastic`. 

Closing for now, feel free to re-open if there's additional issues.

**Comment by ezuk** [comment]
Thanks @justinfrench - that was it. :\ Sorry for the silly report! I'm sure I copied that from somewhere official but can't find it ATM. I appreciate your help!
