### ISSUE TITLE
How it works example doesn't have a form

### ISSUE THREAD

**Issue by mlaco** [justinfrench/formtastic#1147]
[This page](https://github.com/justinfrench/formtastic/wiki/1.1-How-It-Works) says it has an example form on it, but it does not.
![image](https://cloud.githubusercontent.com/assets/4466642/7750727/d4e5c5a0-ffa3-11e4-8ba4-f9024efe4ec9.png)

**Comment by justinfrench** [comment]
Hi, I've just made [this change](https://github.com/justinfrench/formtastic/wiki/1.1-How-It-Works/_compare/8733abcfd44e6b1795162c587cda9528a6d6ad4e%5E...8733abcfd44e6b1795162c587cda9528a6d6ad4e), see if that helps you. The document wasn't updated when Rails changed the way block helpers are rendered.

**Comment by justinfrench** [comment]
Closing for now, please re-open if needed!
