### ISSUE TITLE
Formtastic override a default (as in formtastic class) input

### ISSUE THREAD

**Issue by syndbg** [justinfrench/formtastic#1154]
Say that I want to override the default `f.input :category, as: :select` with my own Select Input.

I can create my own Select Input and use it instead of the default, but always have to specify it as ex. `f.input :category, as: :my_select` everywhere I want to use it.

Or is possible (and how) to override the default :select to get automagically replaced with mine?

**Comment by justinfrench** [comment]
Instead of this:

```
# app/inputs/my_select_input.rb
class MySelectInput < Formtastic::Inputs::SelectInput
  # your implementation or overrides go here
end
```

```
# app/inputs/select_input.rb
class SelectInput < Formtastic::Inputs::SelectInput
  # your implementation or overrides go here
end
```

If you've already implemented `:my_select`, that should be all the info you need, but feel free to re-open if you get stuck somewhere.

**Comment by syndbg** [comment]
Thank you very much @justinfrench
That's exactly what I needed!
