### ISSUE TITLE
treeview in check_boxes

### ISSUE THREAD

**Issue by lica667** [justinfrench/formtastic#1156]
Hello. I'm wondering how can I show in forms 'edit' and 'new' check_boxes by treeview. 
I have categories with many subcategories and in create/update product form I want show categories with usability form. Can formtastic help me?

**Comment by justinfrench** [comment]
There's nothing out-of-the-box sorry. You would need to build a custom input, or just drop into regular Rails helpers. You can mix-and-match Rails forms with Formtastic forms:

```
<%= semantic_form_for(@thing) do |f| %>
  <!-- formtastic stuff -->
  <%= f.input(…) %>

  <!-- regular rails stuff -->
  <li>
    <%= f.checkbox(…) %><%= f.label(…) %>
  <li>
<% end %>
```
