### ISSUE TITLE
Inline hints

### ISSUE THREAD

**Issue by syndbg** [justinfrench/formtastic#1157]
Currently form hints are displayed in `<p>` tags as seen in https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/base/hints.rb

If I want to have `<span>` (inline) hints, my first reaction is to override the way hints are generated or modify the `inline-hints` CSS class, however this approach will surely mess up existing Formtastic usage.

Instead, what do you think about me submitting a PR with a new option for inputs `inline-hint` which will generate a hint with `<span>` and use CSS class 'inline-hints'.

In my opinion this is the cleanest approach. What do you think about this?

Also after exploring the source I don't really agree with <p> hints having a CSS class 'inline-hints', when actually they should be just 'hints' since they're not inline.

**Comment by justinfrench** [comment]
Hi there, the "inline" naming is a bit awkward, but we aren't talking about how you style it, we're talking about its semantics. We borrowed the naming from inline errors. They're not necessarily style to look like they're "in a line", but they're different to Rails' standard "errors at the top of the form". 

By default a paragraph is a block element, but you can style it to be positioned it displayed in a line using many different CSS techniques. 

Changing the paragraph to a span or the name for these things would require a major version bump that I really don't think is necessary.

Closing for now, but let me know if you need help with the CSS or strongly disagree with me 😏



it matches the name for "inline errors", wh

**Comment by syndbg** [comment]
On a semantic-level I don't like making the <p> `display: inline`. And flexibility-wise, with that approach I would limit myself to having every input hint inline. What if I want to have an option between inline or block?

I *don't* propose to change the current *hint* option to <span>. This will break the form for every Formtastic user.

Instead I propose I should add PR for an *inline_hint* option for inputs that would generate the hint using a <span>. It's the cleanest approach to having the option to pick either *hint* or *inline_hint*. Or maybe both. 


P.s What I am trying to achieve here is explain my idea better and possibly green-lit it.

**Comment by justinfrench** [comment]
> On a semantic-level I don't like making the <p> as display: inline.

Why?

> Instead I propose I should add PR for an inline_hint option for inputs that would generate the hint using a <span>. It's the cleanest approach to having the option to pick either hint or inline_hint. Or maybe both.

You're proposing we add something to the `input` DSL which is a _markup preference_ rather than _functionality_ or _content_. I can't think of anywhere else we do this, and I don't think I want to start here. Especially when this is 99% a presentational issue that can easily be resolved with CSS. This is literally the entire thesis of Formtastic :) 

It sounds like you want to do this on a per-input basis, so could you provide me with a mock-up or example of what you're trying to achieve? I'd like to understand the _real_ problem you're trying to solve, beyond `<span>` tags.
