### ISSUE TITLE
Crash in lib/formtastic/inputs/base/validations.rb

### ISSUE THREAD

**Issue by fabien-michel** [justinfrench/formtastic#1161]
Hi, 
there is a bug in lib/formtastic/inputs/base/validations.rb readonly_attributes?

The line ```object_class.readonly_attributes.include?(column.name.to_s)``` suppose column to be not nil.
Some times it is.  Everywhere else in the same file, when column is used, there is always a test for his presence.
I can't propose a patch as I'm not sure of the goal of the method.

**Comment by st0012** [comment]
For the method's goal you can read #1158

**Comment by st0012** [comment]
And I am very sorry about causing this issue...
