### ISSUE TITLE
[SUGGESTION] Provide a way to silence deprecation warnings

### ISSUE THREAD

**Issue by hron84** [justinfrench/formtastic#1168]
We still use Rails 3.2 for our legacy application but we upgraded formtastic to the latest version to be able use new features. However, RSpec started to spam our test log with deprecation warnings making it completely useless.

We understand you are planning to drop Rails 3 support, but please, please do this deprecation thing more nicely and provide a way to make it less obtrusive since this warning become displayed at every single test and this is just a spam and does not do it's intended job.

**Comment by hron84** [comment]
Currently, we use a monkey-patch to avoid this spamming, with this snippet:

```ruby
if Formtastic::Deprecation != ActiveSupport::Deprecation
  module Formtastic
    class Deprecation
      def self.silenced=(new_value)
        self.deprecation.silenced = new_value
      end

      def initialize(version, _library)
        deprecation.deprecation_horizon = version
      end
    end
  end
end
```
It does not silences all deprecation warnings, one or two still appears, but does not spam through the whole test log with useless whining.

**Comment by mikz** [comment]
@hron84 why not just (inside your `config/initializers/formtastic.rb`):

```ruby
Formtastic.deprecation.silenced = true
```

**Comment by hron84** [comment]
Because I checked the Formtastic source, and it resets the deprecation state at the initializer (the original initialzier contains `self.deprecation.silenced = false`), that's why I had to override this, since I do not know where it will be instantiated and become cleared.

**Comment by mikz** [comment]
@hron84 yes, that is when the deprecation object is initialized. That happens when Formtastic is loaded.
You can just set silenced to false whenever you want. There is no magic.

**Comment by hron84** [comment]
@mikz I had no time to go through the whole code and find out when you initialize this setting but usually it's a wrong idea set up a state of the static variable unconditionally during an initializer since you cannot be sure when it will be (re-)initialized. 

Also, could you update README / Wiki about this possibility to save users from fiddling the code too much?
