### ISSUE TITLE
Update RSpec version?

### ISSUE THREAD

**Issue by st0012** [justinfrench/formtastic#1173]
I noticed that formtastic still using `rspec-rails 2.14`, maybe it's better to let `RSpec` and test helpers up-to-date for more maintainable tests.

**Comment by mikz** [comment]
That is being tackled as part of #1170 by @pranas

**Comment by st0012** [comment]
@mikz got it, thanks!

**Comment by mikz** [comment]
RSpec is now 3.3 which is recent enough I'd say. Thanks for bringing it up!
