### ISSUE TITLE
Change readme from textile to markdown

### ISSUE THREAD

**Issue by st0012** [justinfrench/formtastic#1175]
The reason is that Github has better support for markdown, like code block's syntax highlight. And I think this would be helpful for those who wants to use this gem, because there are many sample codes in readme. And markdown also is more common than textile, which means more easy to maintain.

So, what do you think?  @justinfrench @mikz

Btw, I am willing to do the transformation. :smile:

**Comment by justinfrench** [comment]
Sure.

**Comment by mikz** [comment]
:+1:

**Comment by st0012** [comment]
PR #1176

**Comment by st0012** [comment]
Since the PR has been merged, this should be close.
