### ISSUE TITLE
disable_with is not working in rails 4.2.3

### ISSUE THREAD

**Issue by iashanmugavel** [justinfrench/formtastic#1182]
disable_with is not working  in rails 4.2.3. its allowing multiple submit

**Comment by mikz** [comment]
@iashanmugavel could you provide an example of what are you trying?

**Comment by iashanmugavel** [comment]
For example, The below form is accepting multiple(more than one click) submit , while submit. `disable_with` is not disabling once clicked the submit button, before the action is completed.

```ruby
<%= semantic_form_for @user, as: :user , method: :post do |f| %>
  <%= f.inputs do %>  
     <%= f.input :name, label: t(:user_name) %>   
  <% end %>  
  <%= f.actions do %>
     <%= f.action :submit, label: 'Save', button_html: { class: "buttonLink saveButton" , disable_with: 'Please Wait...'} %>
   <% end %>  
<% end %>
```

**Comment by mikz** [comment]
@iashanmugavel passing `disable_with` was deprecated in Rails 4.0 I think. The correct way is:

```
f.action :submit, button_html: { data: { disable_with: 'message' } }
```

See the documentation: http://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html#method-i-submit_tag

**Comment by iashanmugavel** [comment]
Thank you

**Comment by joshuapinter** [comment]
Any idea if there's a place where all of these deprecations are found? We've gotten bit by this one and by the `confirm`. They fail silently so they don't show up in tests typically. Thanks!

**Comment by mikz** [comment]
@joshuapinter I believe they are in the log and since some rails version, you can configure it to raise an exception instead. It can also be backported to older rails quite easily.
