### ISSUE TITLE
Shouldn't it be showing a hidden input if `hidden_fields` is set to be true?

### ISSUE THREAD

**Issue by leomayleomay** [justinfrench/formtastic#1189]
The line https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/check_boxes_input.rb#L102 indicates that an empty string will be returned if `hidden_fields` is set to be true, while a hidden input will be returned if it's set to be false.

While the line https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/check_boxes_input.rb#L173 tells a different story, it will return a hidden input if the `hidden_fields` is set to be true.

It contradicts between each other if I understand it correctly.

**Comment by leomayleomay** [comment]
https://github.com/justinfrench/formtastic/pull/1190

**Comment by sandfoxme** [comment]
If the hidden fields is true then every checkbox has its field, otherwise there's one field for all
This merge broke proper saving of empty check boxes
