### ISSUE TITLE
Hidden Fields

### ISSUE THREAD

**Issue by jduarte** [justinfrench/formtastic#119]
It's impossible to pass a value to a hidden field even if we specify something like:

<%= f.input :object_id, :as => :hidden, :input_html => {:value => @object.id} %>

By the way,

Great work on the plugin! It's becoming really useful!

**Comment by pzi** [comment]
Hello! Has there ever been a solution for this? I'd prefer not having "empty" `li`s in my source... This also messes with screenreaders.

**Comment by justinfrench** [comment]
@pzi on which bit of this thread? Moving the hidden inputs of the list to avoid empty LIs? No progress AFAIK. Feel free to explore this in a PR (preferred) or raise a new issue, there's a high chance that I'd merge this if it were solved, but a low chance that I'll be motivated to do the work myself in the near term :)

**Comment by pzi** [comment]
Yeah, the bit that adds the hidden fields into div of the form, like rails does, as suggested by @grimen.

Unfortunately, I am no Ruby developer. So chances that I can do it myself are very slim. I can raise a new issue for sure though... :)
