### ISSUE TITLE
Release Formtastic 3.1.4

### ISSUE THREAD

**Issue by mikz** [justinfrench/formtastic#1198]
Formtastic 3.1.4 will be last release of 3.1 series. 

The PR containing all changes is https://github.com/justinfrench/formtastic/pull/1194
As proposed in https://github.com/justinfrench/formtastic/pull/1108#issuecomment-187905777 there are several tasks to be done in order to release a stable version.

# TODO

- [x] review #1194 has no breaking changes
- [x] review #1194 has correct changelog
- [x] merge #1194
- [x] tag 3.1.4
- [x] release 3.14
- [ ] continue with #1197

**Comment by justinfrench** [comment]
@mikz would you like me to merge #1194 and tag/push the gem?

**Comment by mikz** [comment]
@justinfrench Think so. Imo there are no breaking changes, changelog looks complete. Should be good.

**Comment by justinfrench** [comment]
@mikz Released 3.1.4. Thanks so much for your hard work on this!

**Comment by justinfrench** [comment]
Closing issue.
