### ISSUE TITLE
justinfrench shouldn't be the only one who can push new gems

### ISSUE THREAD

**Issue by justinfrench** [justinfrench/formtastic#1200]
This is a bad situation to be in for a popular open source project.

At the very least, I think at least one other maintainer with commit rights should have the rights to push new gems as well. Based on recent efforts, the most obvious choice is @mikz.

Maybe it should be all committers, maybe that list needs revising.

**Comment by mikz** [comment]
Just for the record, y rubygems profile is https://rubygems.org/profiles/mikz

**Comment by sandfoxme** [comment]
I'm sorry for the references above, I copy-pasted wrong link

**Comment by justinfrench** [comment]
I've added @mikz as an owner on RubyGems.org, so this is finally resolved. Please confirm and let ,me know if you need any more guidance on this @mikz!

![2017-08-11 at 3 59 pm](https://user-images.githubusercontent.com/5240/29202737-4cced724-7eae-11e7-9a21-1f72b79ecad3.png)

**Comment by mikz** [comment]
@justinfrench looks like I have access, thank you!
