### ISSUE TITLE
Need to switch off inline errors for an attribute

### ISSUE THREAD

**Issue by clubbavi** [justinfrench/formtastic#1214]
Hello,

Can we switch off inline errrors for a specific attribute?

Thanks,
Avinash

**Comment by mikz** [comment]
Don't think so. But you can just hide them by css for example.
Or you can create own input type that overrides the `error_html` method like [hidden input does](https://github.com/justinfrench/formtastic/blob/5790fb6ba1f9d5dd45c71c4c731db477111e4245/lib/formtastic/inputs/hidden_input.rb#L44-L46).

**Comment by clubbavi** [comment]
Ok, so we do that through css. It would be a good feature though.

**Comment by mikz** [comment]
Agree. We could consider it for 4.0. Contributions welcome!
