### ISSUE TITLE
best way to change/override label for password?

### ISSUE THREAD

**Issue by niksfirefly** [justinfrench/formtastic#1215]
I want to put link to JS action in password field label
I wonder what is the best option to create second line in label part of password input?

**Comment by mikz** [comment]
You can just pass any string/html to the input in `label:` parameter. It can be from i18n, partial, ...
Or you can just use a symbol [ending with `_html`](http://guides.rubyonrails.org/i18n.html#using-safe-html-translations) and add the proper key to the i18n file.

**Comment by niksfirefly** [comment]
thx
nevertheless there are 2 problems
1.formtastic defaults strip html tags for hints and labels
2.attr required comes after label - so our string become marked as required - not so elegant

I ended up with with monkey patch for label_text and i18n support for new type in formtastic localization
