### ISSUE TITLE
Numericality validation problem

### ISSUE THREAD

**Issue by nicolas-besnard** [justinfrench/formtastic#1228]
When using `numericality` with `greater_than: :other_field` where `:other_field` is a field on your model, the [following line](https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/base/validations.rb#L103) break.

My code:

``` ruby
validates :minimum_turnover_in_cents,
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 0
    }

  validates :maximum_turnover_in_cents,
    numericality: {
      only_integer: true,
      greater_than: :minimum_turnover_in_cents
    }
```

**Comment by mikz** [comment]
I'm happy to merge a patch testing and fixing this.
