### ISSUE TITLE
how to modify the default min and max years for date inputs

### ISSUE THREAD

**Issue by lauraeci** [justinfrench/formtastic#1237]
![screen shot 2017-01-17 at 12 24 02 pm](https://cloud.githubusercontent.com/assets/1151330/22043000/78507cce-dcc2-11e6-8677-ca262b2f84e6.png)

I'm using a date input type and would like to know how to customize the min and max date range. Currently, all my employees have birthdates after 2012.  I would prefer not to use the Datepicker as I like the ability to select from a dropdown of years and not scroll through a calendar. 

Thank you.

**Comment by lauraeci** [comment]
Found the solution in a Rails cast: http://railscasts.com/episodes/184-formtastic-part-1?view=asciicast

It would be useful to have the start_year option in the docs.  Thank you.

**Comment by mikz** [comment]
@lauraeci contributions always welcome!

**Comment by lauraeci** [comment]
Hi @mikz, happy to help add documentation.  Let me know how and where to add it and I can take a stab at a doc PR.

**Comment by mikz** [comment]
@lauraeci I think that could be good if you could think of a way where you'd look for this documentation. Because if we would put it on a place, where you didn't look, it would not help.

Not sure if you checked RDoc, Wiki or just the Readme.
