### ISSUE TITLE
default_columns_for_object returns duplicates

### ISSUE THREAD

**Issue by Fivell** [justinfrench/formtastic#1240]
refs https://github.com/activeadmin/activeadmin/issues/3828

Example 
```ruby
class Consent < ActiveRecord::Base
  belongs_to :disclosed_from_org, :class_name => "Organization", :foreign_key => "disclosed_from_orid"
  belongs_to :disclosed_to_org, :class_name => "Organization", :foreign_key => "disclosed_to_orid"
end
```

When trying to build form for such configuration  it displays duplicated inputs for each association.

After debugging I detected problematic method
```ruby
/formtastic-3.1.4/lib/formtastic/helpers/inputs_helper.rb
```

method ```default_columns_for_object```

```
 def default_columns_for_object
        cols  = association_columns(:belongs_to)
        cols += content_columns
        cols -= Formtastic::FormBuilder.skipped_columns
        cols.compact
  end
```

~~for  this case  ```disclosed_from_orid``` and  ```disclosed_to_orid``` exists in both~~

```
 association_columns(:belongs_to)
``` 
and 
```
content_columns
```

I think formtastic should skip element from content_columns  if already exits in ```association_columns(:belongs_to)```

UPD ```content_columns```  contains  ```disclosed_from_orid``` and  ```disclosed_to_orid```
and  ``` association_columns(:belongs_to)```  contains ```disclosed_from_org``` and ```disclosed_to_org``` 
that is the reason of duplicates as well

**Comment by Fivell** [comment]
btw @justinfrench  maybe formtastic has possibility to override ```default_columns_for_object``` ?

**Comment by Fivell** [comment]
cc @mikz

**Comment by mikz** [comment]
I see. I suppose the column names are all symbols/strings ? Would it make sense to use set instead or call `.uniq` ? It is hard to imagine a scenario where you'd like to have duplicates.

Would be good to have some example schema of the model. The original issue says it shows two drop downs and two text fields which would not indicate a symbol/string array.

**Comment by Fivell** [comment]
@mikz ,
> The original issue says it shows two drop downs and two text fields which would not indicate a symbol/string array.

 it shows 
dropdown for ```disclosed_to_org```   because is returned by ```association_columns(:belongs_to)```
dropdown for ```disclosed_from_org``` because is returned by ```association_columns(:belongs_to)``` 
input for  ```disclosed_from_orid```  because is returned by ```content_columns```
and input for ```disclosed_to_orid```  because is returned by ```content_columns```


Formtastic think that ```content_columns``` skip this foreign keys, however content_columns is very stupid and just remove columns then end with ```id```


>>I see. I suppose the column names are all symbols/strings ? Would it make sense to use set instead or call .uniq ?

I think no, check my comment above

>> content_columns contains disclosed_from_orid and disclosed_to_orid
and association_columns(:belongs_to) contains disclosed_from_org and disclosed_to_org
that is the reason of duplicates as well


There are duplicates in logical sense, array of inputs still are unique


Example of schema
```ruby
create_table "categories", force: true do |t|
    t.string   "title"
    t.text     "description"
end
 
create_table "products", force: true do |t|
    t.string   "title"
    t.text     "description"
    t.decimal  "price"
    t.boolean  "featured"
    t.integer  "main_category"
    t.integer  "secondary_category"
 end

class Product < ActiveRecord::Base
  belongs_to :primary_product_category, foreign_key: :main_category 
  belongs_to :secondary_product_category, foreign_key: :secondary_category
end

```

**Comment by mikz** [comment]
So it falls apart when using custom foreign keys that don't end with `_id`, right?

I'd say to fix this properly the  `content_columns` method should detect and check if there are any associations defined with that foreign key.

**Comment by Fivell** [comment]
@mikz , right, but ```content_colums``` is rails method and it doesn't check foreign keys at all. 
see this http://apidock.com/rails/ActiveRecord/ModelSchema/ClassMethods/content_columns

**Comment by mikz** [comment]
Formtastic wraps it in its own `content_columns` https://github.com/justinfrench/formtastic/blob/b104bb1fe5228ea37f668917b13d0888f8bd033a/lib/formtastic/helpers/inputs_helper.rb#L353-L359
So it can easily filter columns that belong to associations.

**Comment by Fivell** [comment]
@mikz , ok now I see, so you're confirming this is bug in formtastic ```content_columns```  ?

**Comment by mikz** [comment]
I'm not calling it a bug. It is definitely an edge case and filtering those `content_columns` would be an improvement to the auto detection feature.

But yes, this should be implemented on Formtastic side. Contributions welcome.

**Comment by Fivell** [comment]
@mikz , would be nice if you could assist me about where I can put test for this , because I'm not familiar with formtastic test infrastructure

**Comment by mikz** [comment]
It is pity, that the helper methods are protected.

So I'd extract those content/association methods into a class like `Formtastic::ColumnDetection` and test it independently. And just delegate from those old helpers to the new class.

Then one integration test in https://github.com/justinfrench/formtastic/blob/b104bb1fe5228ea37f668917b13d0888f8bd033a/spec/helpers/inputs_helper_spec.rb would have to mock rails `content_columns` on the model like:

https://github.com/justinfrench/formtastic/blob/b104bb1fe5228ea37f668917b13d0888f8bd033a/spec/spec_helper.rb#L298-L299

Unfortunately there is no suite using real db schema yet.

Does that help?

**Comment by Fivell** [comment]
@mikz , need time to investigate this, not sure I will be able to do this next days

**Comment by mikz** [comment]
We have ongoing 4.0 release that takes more time than I wanted. So you have plenty of time to make it into 4.0.

**Comment by Fivell** [comment]
@mikz , I will add failing test case as first step
