### ISSUE TITLE
Patch for version 3.1.4 to fix ruby 2.4 deprecation warnings

### ISSUE THREAD

**Issue by Mbuckley0** [justinfrench/formtastic#1243]
Is it possible to do a patch release of version 3.1.4 to fix the deprecation warnings after upgrading to ruby 2.4

**Comment by mikz** [comment]
That would be backporting https://github.com/justinfrench/formtastic/pull/1235 right?

Can you confirm all deprecation warnings are gone with that? Then I could prepare a tag but @justinfrench would have to do the actual release to rubygems.

**Comment by Mbuckley0** [comment]
I can confirm that using that branch removes all of the formtastic deprecation warnings.
