### ISSUE TITLE
Error undefined select_año due to translations to spanish

### ISSUE THREAD

**Issue by antprt** [justinfrench/formtastic#1257]
I have an error with formtastic.

My application has two languages spanish and english.

When I try to edit a register with a date formtastic raise Exception "undefined select_año". Only occurs with dates created by other gem. Never with created_at and updated_at that are created by rails.

año is year in spanish. If I have the application only in english the problem never happens. I suppose that in that case the application search "select_year" instead of "select_año"

Does someone knows how to avoid this error? Where is the translation? Why does I have that error?

**Comment by mikz** [comment]
Would be good to send the backtrace to see where exactly is this happening.

I assume the column name is not in Spanish, right?

**Comment by antprt** [comment]
The column in DB is in english. Is called birthdate.

Yesterday I realized where was the translation. If I put that in my es.yml the exception occurs:

es:
  date:
    # Used in date_select and datetime_select.
    order:
      - año
      - mes
      - dia

If I write instead of año, mes, día; year, month and day the gem works.
I use formtastic because is included in activeadmin gem. I haven't configured the forms manually because is done by activeadmin gem.

My question now is why? What does formtastic does with this translation? Why does occurs the exception? can't I translate to spanish ever?

The full backtrace is:

ActionView::Template::Error: undefined method `select_año' for #<#<Class:0x007f25f1083ef0>:0x007f25f1142968>
Did you mean?  select_day
               select_tag
               select_date
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:165:in `fragment_input_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:102:in `block (4 levels) in to_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:39:in `capture'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:128:in `fragment_wrapping'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:100:in `block (3 levels) in to_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:99:in `map'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:99:in `block (2 levels) in to_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:39:in `capture'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:200:in `fragments_wrapping'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:95:in `block in to_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/helpers/capture_helper.rb:39:in `capture'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/wrapping.rb:11:in `input_wrapping'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/form_builder.rb:6:in `input_wrapping'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/inputs/base/timeish.rb:94:in `to_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/helpers/input_helper.rb:242:in `input'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/helpers/inputs_helper.rb:330:in `block in fieldset_contents_from_column_list'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/helpers/inputs_helper.rb:318:in `collect'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/helpers/inputs_helper.rb:318:in `fieldset_contents_from_column_list'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/formtastic-3.1.5/lib/formtastic/helpers/inputs_helper.rb:297:in `inputs'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/rails/forms.rb:30:in `proxy_call_to_form'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/components/active_admin_form.rb:60:in `inputs'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/form.rb:45:in `block in default_form_config'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/components/active_admin_form.rb:35:in `instance_eval'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/components/active_admin_form.rb:35:in `build'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/form.rb:25:in `main_content'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:93:in `block (2 levels) in build_main_content_wrapper'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:92:in `block in build_main_content_wrapper'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:91:in `build_main_content_wrapper'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:77:in `block in build_page_content'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:76:in `build_page_content'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:54:in `block (2 levels) in build_page'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:14:in `div'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:50:in `block in build_page'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:49:in `build_page'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/lib/active_admin/views/pages/base.rb:10:in `build'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:92:in `with_current_arbre_element'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:26:in `build_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/app/views/active_admin/resource/edit.html.arb:2:in `block in __home_user__rvm_gems_ruby_______gems_activeadmin_______app_views_active_admin_resource_edit_html_arb__3153189010499810165_69900467553500'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:45:in `instance_eval'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/arbre-1.1.1/lib/arbre/context.rb:45:in `initialize'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/app/views/active_admin/resource/edit.html.arb:1:in `new'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.0.0/app/views/active_admin/resource/edit.html.arb:1:in `__home_user__rvm_gems_ruby_______gems_activeadmin_______app_views_active_admin_resource_edit_html_arb__3153189010499810165_69900467553500'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/template.rb:159:in `block in render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/template.rb:354:in `instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/template.rb:157:in `render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-mini-profiler-0.10.6/lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/template_renderer.rb:14:in `render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/renderer.rb:42:in `render_template'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/renderer/renderer.rb:23:in `render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/rendering.rb:104:in `_render_template'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/streaming.rb:217:in `_render_template'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/rendering.rb:83:in `render_to_body'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/abstract_controller/rendering.rb:26:in `render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/rendering.rb:36:in `render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
	from /home/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.2/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:43:in `render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/wicked_pdf-1.1.0/lib/wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/wicked_pdf-1.1.0/lib/wicked_pdf/pdf_helper.rb:27:in `render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/responders-2.4.0/lib/action_controller/responder.rb:238:in `default_render'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/responders-2.4.0/lib/action_controller/responder.rb:170:in `to_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/responders-2.4.0/lib/responders/flash_responder.rb:107:in `to_html'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/responders-2.4.0/lib/action_controller/responder.rb:163:in `respond'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/responders-2.4.0/lib/action_controller/responder.rb:156:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/responders-2.4.0/lib/action_controller/respond_with.rb:211:in `respond_with'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/inherited_resources-1.7.2/lib/inherited_resources/actions.rb:25:in `edit'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/abstract_controller/base.rb:188:in `process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/route_translator-5.5.0/lib/route_translator/extensions/action_controller.rb:23:in `set_locale_from_url'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:382:in `block in make_lambda'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:285:in `block in halting'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:447:in `block in around'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/abstract_controller/base.rb:126:in `process'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionview-5.0.2/lib/action_view/rendering.rb:30:in `process'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-mini-profiler-0.10.6/lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal.rb:190:in `dispatch'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_controller/metal.rb:262:in `dispatch'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:39:in `block in serve'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `each'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `serve'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:725:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/omniauth-1.7.1/lib/omniauth/builder.rb:63:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/bullet-5.6.1/lib/bullet/rack.rb:10:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/meta_request-0.4.3/lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/meta_request-0.4.3/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.2/lib/active_record/migration.rb:553:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-contrib-1.2.0/lib/rack/contrib/response_headers.rb:17:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/meta_request-0.4.3/lib/meta_request/middlewares/headers.rb:16:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `block in call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/rack-mini-profiler-0.10.6/lib/mini_profiler/profiler.rb:282:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
	from /home/user/.rvm/gems/ruby-2.4.1/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by mikz** [comment]
So it fails because of `i18n_date_fragments` https://github.com/justinfrench/formtastic/blob/f0a3b1c2e69aa09d8fe4ad3796c3a313dec73ef6/lib/formtastic/inputs/base/timeish.rb#L189-L196 

From the official Spanish i18n https://github.com/svenfuchs/rails-i18n/blob/063b39cc366bd19dfc80dd8f975c8b570214df19/rails/locale/es.yml#L59-L62 those values should be always in English because that is how Rails expects it.

So I'd suggest to use the official Spanish i18n file. This is not a formtastic issue.
