### ISSUE TITLE
span inside f.lable in haml

### ISSUE THREAD

**Issue by SimonSharville** [justinfrench/formtastic#1259]
Hi, I'm trying to add a span inside a =f.label in ruby, written in haml but I cant, get it to work, any help would be much appreciated. Is there another way of doing it, I've resaerched but nothing I try works.

.form-group.sa-checkboxes
  .checkbox.sa-checkbox
    = f.check_box :edoc_uploaded
    = f.label :edoc_uploaded, "An eDocument is uploaded by a delegate or administrator"
      %psan.checkbox

**Comment by mikz** [comment]
```erb
= f.label :somefield, render(partial: 'some_partial')
```

Or make some helper that will render a haml block and pass it as a param to `f.label`.
But this is not HAML support and not Formtastic specific question.

Closing this issue. Feel free to reopen if you have some feature suggestion or a bug report.
