### ISSUE TITLE
How to set up a form's with a drop down that includes X choices plus a "free" input

### ISSUE THREAD

**Issue by misner** [justinfrench/formtastic#1261]
I would like to set up for a Active-Admin formtastic form a field we can call field_example (string type), a basic dropdown that would show:

- option 1
- option 2
- option 3
- freely inputed field

Is it possible with Formtastic  to enable the user to choose of the 3 basic options but if he does not recognize himself in those 3 options, be able to type freely another string (this string would not have to be added to the list of options for future forms edition). He could type anything.

My code today:

**admin/model.rb**

    f.input :field_example,
            as:         :select,
            collection: LIST_OF_OPTIONS,
            prompt:     true

**config/initializers/active_admin_constants**

    LIST_OF_OPTIONS = ["option1","option2", "option3"]

**Comment by mikz** [comment]
Formtastic is just a form generator. It does not say how you want to design your inputs.
You need to figure out how you want to have this in HTML+JS and then create those inputs by formtastic.

This is not responsibility of Formtastic. Closing this issue.
Feel free to reopen if if there is some feature request.

**Comment by misner** [comment]
Ok, dully noted. Thanks.
