### ISSUE TITLE
Required input doesn't work

### ISSUE THREAD

**Issue by stadniklksndr** [justinfrench/formtastic#1262]
Formtastic validation not working

f.input :contact_id, as: :select, collection: Contact.all.map {|c| [c.name, c.id]}, required: true

Do you have any suggestions how to add "required: true"?

**Comment by mikz** [comment]
It is hard to guess what "not working" means. The browser validation? Rails validation?

There are settings to enable the browser validation for select/option: https://github.com/justinfrench/formtastic/blob/b104bb1fe5228ea37f668917b13d0888f8bd033a/lib/generators/templates/formtastic.rb#L83-L85

Next time would be better to explain what you did, what was the html and what you expected instead.

**Comment by stadniklksndr** [comment]
I meant the browser validation.

Configs below helped me.
Formtastic::FormBuilder.use_required_attribute = true
Formtastic::FormBuilder.perform_browser_validations = true

Now browser validation works.
Thank you @mikz
