### ISSUE TITLE
Execute custom code on submit?

### ISSUE THREAD

**Issue by tlhinman** [justinfrench/formtastic#1290]
Hello! We're using Formtastic with our Active Admin. Is there any way to get some custom Ruby code to run when the Submit button is clicked? It's set up like this:

```ruby
f.actions do
  confirmation_message = "Are you sure?"
  f.action(:submit, button_html: {"data-confirm".to_sym => confirmation_message})
  f.cancel_link
end
```

Thanks!

**Comment by justinfrench** [comment]
Formtastic only helps you build up the HTML form. If you want Ruby code to run on the server, that's what the controller needs to do after you submit. If you want code to run on the client side (which is what you want to do here with a confirmation dialogue), then Formtastic can help you build the necessary HTML, but not execute it on the client side.

This is a good way to use Formtastic to generate some usable form HTML:

```
f.actions do
  f.action(:submit, button_html: {"data-confirm".to_sym => "Are you sure?"})
  f.cancel_link
end
```

… but _something else_ (in ActiveAdmin, I guess) needs to add some Javascript to the page that listens for clicks on "data-confirm" buttons and adds a confirmation step.
