### ISSUE TITLE
Read only field

### ISSUE THREAD

**Issue by eltados** [justinfrench/formtastic#171]
I think it would be easy enough and quit a useful feature to actually be able to do something like:

```
<% form.inputs do %>
   <%= form.input :title , readonly => true %>
 <% end %>
```

or 

```
 <% form.inputs do %>
    <%= form.readonly :title  %>
 <% end %>
```

 that would render the normal label and instead of the field would create a span with value properly displayed Date format, number etc ?

**Comment by jtomaszewski** [comment]
I had the same common issue in my app. So what I did, is I created a `ReadonlyInput`, that now I use here and there:

```rb
# app/inputs/readonly_input.rb
class ReadonlyInput < Formtastic::Inputs::StringInput
  def to_html
    input_wrapping do
      label_html <<
      template.pretty_format(object.send(method)) # or some other way to format the value in a nice way
    end
  end
end

# example usage, f.e. in my activeadmin app:
if f.object.persisted? && f.object.class.readonly_attributes.include?("parent_id")
  f.input :parent, as: :readonly
else
  f.input :parent
end
```

**Comment by mikz** [comment]
@jtomaszewski :+1: that is the correct approach I'd say. Also you could also create own `StringInput`, that has the `object.persisted? && readonly_attribute?("#{method}_id")` logic. It would be more magic, but it could reduce the logic in the view. Then all the inputs would appear as readonly automatically.

**Comment by Adeynack** [comment]
@jtomaszewski : I have the problem with that approach that the field in question is set to `nil` on submit. Did you have to mitigate that when you used your `ReadonlyInput`?
