### ISSUE TITLE
Select with grouping error

### ISSUE THREAD

**Issue by voldy** [justinfrench/formtastic#184]
Given
    class Category < ActiveRecord::Base
      belongs_to :parent, :class_name => "Category", :foreign_key => "parent_id"
      has_many :children, :class_name => "Category", :foreign_key => "parent_id"
    end
And
    class Item < ActiveRecord::Base
      belongs_to :category
    end
As I figured out that should work:
    = f.input :category, :include_blank => false, :group_by => :parent
but I run into error:
    undefined local variable or method `object_class' for #Formtastic::SemanticFormBuilder:0x87d3158
It seems that the problem is in **detect_group_association** method.

**Comment by danielricecodes** [comment]
Thought I'd make an update here.  You can also use `grouped_options_for_select` if the `option_groups_from_collection_for_select` doesn't work with your particular use case.  For me, I had a Rails STI table of Options that I needed to convert into a multiple select box.  I munged on my data using this particularly unreadable bit of Ruby code...the end result is a hash that `grouped_options_for_select` expects.  Hope this helps other who land here like I did.

```ruby
      f.input :engagement_form_options, 
        as: :select2_multiple,
        collection: grouped_options_for_select(
          EngagementFormOption.order(:type, :name).pluck(:name, :id, :type).group_by(&:last).inject({}) do |memo, (k,v)|
            memo.merge!(k.titleize => v.map{|vm| vm[0..1]})
          end,
          f.object.engagement_form_option_ids
        )
```
