### ISSUE TITLE
Label and boolean input type

### ISSUE THREAD

**Issue by agn507** [justinfrench/formtastic#482]
Attempted to set label to false on a boolean input type and found the checkbox no longer shows up.  This is due to the checkbox being rendered inside the label tag so the element can sit to the left of the text.  Is this intentional and is there any reason why the checkbox can't be moved outside of the label tag?  

I know there are some pretty simple work arounds and this really doesn't get in the way much. Just seems inconsistent with the way setting label to false works with the rest of the input types.

**Comment by asadakbar** [comment]
I know its been a while for this issue but updating for others that come across this. I hit this inconsistency and solved it with `label: ""`. Its a hack but I wanted to independently handle the label and this was the only way to get the boolean input to stop showing the built in label.

**Comment by nidhi-soni1104** [comment]
Hello Guys

I am receiving warning for member_label and member_hint when I am upgrading to  **gem 'formtastic', '~> 4.0'**


  ```
      = f.input :enabled_notifications, as: :check_boxes_with_hints,
                                          collection: category.notifications,
                                          member_label: ->(value) { t(value, scope: :notification_preference_titles) },
                                          member_hint: ->(value) { t(value, scope: :notification_preference_hints) }

```

So when  I tried to update it with this, now labels don't work here
`        = f.input :enabled_notifications, as: :check_boxes, collection: category.notifications

`
So In next step I tried this, which didn't changed anything
        = f.input :enabled_notifications, as: :check_boxes, collection: category.notifications, label: "My label"
        
   How Can I add labels and hints to the checkboxes
   
   **it looks like this** 
      
![image](https://github.com/formtastic/formtastic/assets/84672731/af6da66e-3de9-4e8d-a7ef-cd52153525c9)


but it should look like this 

![image](https://github.com/formtastic/formtastic/assets/84672731/58c83e51-2410-45e0-b177-9bed24290f03)
