### ISSUE TITLE
date strftime + strings

### ISSUE THREAD

**Issue by anathematic** [justinfrench/formtastic#688]
Potentially silly question:

I deal with lots of dates in my application which are in dd/mm/yy and as strings (using jquery's datepicker) - is there a prebuilt way in formtastic to format all of these fields for me?

I know this is something I could do at model level but thought maybe there's something I can do in the forms and dry it all up a bit.

Cheers!

**Comment by davemate23** [comment]
Has there been a formal solution for date localisation in a more recent update?

**Comment by justinfrench** [comment]
@davemate23 I don't think so sorry. The "right way" right now is to use the `:value` option. We have some hardcoded string formatting in https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/datetime_picker_input.rb#L92-L99, so if you'd like to see some stuff based on the current locale, that would be the place to monkey patch it in (or better yet, start working on a pull request).

If you'd like to talk further, please open a separate issue.
