### ISSUE TITLE
Add :member_html option for :select inputs

### ISSUE THREAD

**Issue by shuber** [justinfrench/formtastic#695]
I'd like to be able to add attributes to each `<option>` tag in a `:select` input.

Since the `:input_html` option only seems to add attributes to the `<select>` tag, I have to manually build the option tags and pass them thru as the `:collection` option. A `:member_html` option that works similar to `:member_label` and `:member_value` would be convenient for cases like this.

``` erb
<%= f.input :parent,
            :collection => Page.all,
            :member_html => proc { |page| { 'data-uri' => page.uri } },
            :member_label => :name %>
```

**Comment by robomc** [comment]
Neither of the two supported methods are particularly easy - especially in a context like ActiveAdmin. I'd love to see this :member_html Proc capability.
