### ISSUE TITLE
:wrapper_html => false

### ISSUE THREAD

**Issue by ryanisinallofus** [justinfrench/formtastic#712]
The forced li is nice, as is the associated coding forms talk but there are times where you just NEED to not have any wrapper html. It would be really cool if we could just set it to false.

**Comment by adiakritos** [comment]
Is it hard to make the <li> wrapping html go away? I have an issue here as well and an option to remove those tags when I need to would be a very nice to have. I have to work around them presently.

**Comment by betodasilva** [comment]
When we have nested forms the generated html makes the code too trash. I think that an option to remove the html would be nice.

**Comment by joshudev** [comment]
In case anyone finds it useful, you can patch as follows, in order to change the wrapper tag from an LI to something else (I am using for generating tables). You could easily modify the code to disable the wrapper altogether.

```
# lib/formtastic/inputs/base/wrapping.rb
module Formtastic
  module Inputs
    module Base
      module Wrapping
        def input_wrapping(&block)
          tag = options.fetch(:wrapper_html, {}).delete(:tag) || 'li'
          template.content_tag(tag,
           [template.capture(&block), error_html, hint_html].join("\n").html_safe,
           wrapper_html_options
          )
        end
      end
    end
  end
end
```

It can be used as follows:
`= f.input :name, wrapper_html: { tag: :td }`

**Comment by chrisgeek** [comment]
I am facing this same problem, it would be nice if the `li` wrapper is made optional really, or if the wrapper can be completely taken off just like with simpleform, I am using ActiveAdmin so i am basically stuck with formtastic.
