### ISSUE TITLE
maxlength 4 for integer attributes

### ISSUE THREAD

**Issue by jnimety** [justinfrench/formtastic#728]
rails 3.0.10, mysql2 0.2.13

all of my integer attributes are rendered with a maxlength=4, IE and FF honor this limit and this is an incorrect maxlength for int(11) columns.  Setting maxlength via css is not possible, is there another solution I'm overlooking?

```
<input id="organization_asset_size" maxlength="4" name="organization[asset_size]" step="any" type="number">

create_table "organization", :force => true do |t|
   t.integer  "asset_size"
end

Create Table: CREATE TABLE `organization` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `asset_size` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8
```

**Comment by IrinaBron** [comment]
Hi,  I seem to be running into this issue as well after upgrading Rails:

Rails 5.2.4.4
ActiveAdmin 1.4.3
Formtastic 3.1.5
