### ISSUE TITLE
Multiple input for collection.

### ISSUE THREAD

**Issue by mishatatinets** [justinfrench/formtastic#867]
I have a issue with select input.
If use single insert it works fine, but when I pass multiple => true 

```
  f.input :category_id,
              :as => select,
              :multiple => true,
              :input_html => { :class => "chosen-input",  :style => "width: 700px;"},
              :collection => Category.all
```

I have  a weird in put into database that stars with empty insert. Looks like it sending data to_yaml or simply separates them by "\n-"(my guess, it split by new lines )

Here what I get in console 

["category_id", "---\n- ''\n- '180'\n- '288'\n- '392'\n"]

I wonder why it passing an empty string, and how I can get rid of it. 

I guess I need changing existing input behavior,  but not sure which one. My purpose is to record string of comma separated ids.

**Comment by juggleross** [comment]
It's work for me: 
`  permit_params category_ids: []
input :category_ids, collection: Category.all.collect {|x| [x.name, x.id]}, as: :select, multiple: true, input_html: { class: "chosen-input",  style: "width: 700px;"}`
