### ISSUE TITLE
f.action :cancel, :as => :button doesn't work as expected

### ISSUE THREAD

**Issue by mdorfin** [justinfrench/formtastic#890]
I get `Formtastic::UnsupportedMethodForAction` with this code:

```
30: 
31:     = f.actions do
32:       = f.action :cancel, :as => :button 
33: 
```

I thought it generates a button.

**Comment by asecondwill** [comment]
Leave this here in case somebody else is wondering how.  

`f.action :cancel, :as => :link, label: 'Cancel',  wrapper_html: {class: :cancel}`
